language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
env:
  - FEATURES=""
  - FEATURES="serde"
script:
  - cargo build --verbose --no-default-features --features "$FEATURES"
  - cargo test --verbose --no-default-features --features "$FEATURES"
matrix:
  allow_failures:
    - rust: nightly
