[package]
name = "inth-oauth2"
version = "0.10.0"

description = "OAuth2 client"
keywords = ["authentication", "authorization", "auth", "oauth"]

authors = ["Curtis McEnroe <programble@gmail.com>"]
license = "ISC"

documentation = "https://cmcenroe.me/inth-oauth2/inth_oauth2"
repository = "https://github.com/programble/inth-oauth2"
readme = "README.md"

[dependencies]
chrono = { version = "0.3", features = ["serde"] }
hyper = "0.10"
serde = "1.0.8"
serde_derive = "1.0.5"
serde_json = "1.0.2"
url = "1.1.0"

[dev-dependencies]
hyper-native-tls = "0.2"
yup-hyper-mock = "2.0"
